- name: write the POM
  template:
    src: pom.xml.j2
    dest: /target/pom.xml
- name: create src directory
  file:
    path: '{{ basePackage }}'
    state: directory
- name: write the Base class
  template:
    src: Base.java.j2
    dest: '{{ basePackage }}/{{appName}}.java'
- name: create domain directory
  file:
    path: '{{ basePackage }}/domain'
    state: directory
- name: write the Entity classes
  loop: "{{ (domain.relations|selectattr('name','equalto','entities')|first).children|list }}"
  vars:
    entity: "{{ item }}"
    fields: "{{ (entity.relations|selectattr('name','equalto','fields')|first).children|list }}"
  template:
    src: "Entity.java.j2"
    dest: "{{ basePackage }}/domain/{{entity.name}}.java"
- name: create repository directory
  file:
    path: '{{ basePackage }}/repository'
    state: directory
- name: write the Repository classes
  loop: "{{ (domain.relations|selectattr('name','equalto','entities')|first).children|list  }}"
  vars:
    entity: "{{ item }}"
    fields: "{{ (entity.relations|selectattr('name','equalto','fields')|first).children }}"
  template:
    src: "Repository.java.j2"
    dest: "{{ basePackage }}/repository/{{entity.name}}Repository.java"
- name: create controller directory
  file:
    path: '{{ basePackage }}/controller'
    state: directory
- name: write the Controller classes
  loop: "{{ (domain.relations|selectattr('name','equalto','entities')|first).children|list  }}"
  vars:
    entity: "{{ item }}"
    fields: "{{ (entity.relations|selectattr('name','equalto','fields')|first).children }}"
  template:
    src: "Controller.java.j2"
    dest: "{{ basePackage }}/controller/{{entity.name}}Controller.java"
- name: create resources directory
  file:
    path: '/target/src/main/resources'
    state: directory
- name: write the application.yml
  template:
    src: application.yml.j2
    dest: '/target/src/main/resources/application.yml'
- name: create migration directory
  file:
    path: '/target/src/main/resources/db/migration'
    state: directory
- name: write Flyway migrations
  template:
    src: V1__init.sql.j2
    dest: '/target/src/main/resources/db/migration/V1__init.sql'
- name: write Dockerfile
  template:
    src: Dockerfile.j2
    dest: '/target/Dockerfile'
- name: write docker-compose
  template:
    src: docker-compose.yml.j2
    dest: '/target/docker-compose.yml'